# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\" \n\x10InferenceRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x11InferenceResponse\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x32]\n\x10InferenceService\x12I\n\x0cPredictClass\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=30
  _globals['_INFERENCEREQUEST']._serialized_end=62
  _globals['_INFERENCERESPONSE']._serialized_start=64
  _globals['_INFERENCERESPONSE']._serialized_end=101
  _globals['_INFERENCESERVICE']._serialized_start=103
  _globals['_INFERENCESERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
