# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommend.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'recommend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecommend.proto\x12\trecommend\";\n\x0eUserRecRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\t\n\x01k\x18\x03 \x01(\x05\"(\n\x0cStateRequest\x12\r\n\x05state\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\"\'\n\x0fRecListResponse\x12\x14\n\x0c\x62usiness_ids\x18\x01 \x03(\t\"/\n\x06RecRow\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x62usiness_ids\x18\x02 \x03(\t2\xe4\x01\n\x15RecommendationService\x12\x44\n\x0bGetUserRecs\x12\x19.recommend.UserRecRequest\x1a\x1a.recommend.RecListResponse\x12\x46\n\x0fGetStateHotlist\x12\x17.recommend.StateRequest\x1a\x1a.recommend.RecListResponse\x12=\n\rPredictMatrix\x12\x17.recommend.StateRequest\x1a\x11.recommend.RecRow0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERRECREQUEST']._serialized_start=30
  _globals['_USERRECREQUEST']._serialized_end=89
  _globals['_STATEREQUEST']._serialized_start=91
  _globals['_STATEREQUEST']._serialized_end=131
  _globals['_RECLISTRESPONSE']._serialized_start=133
  _globals['_RECLISTRESPONSE']._serialized_end=172
  _globals['_RECROW']._serialized_start=174
  _globals['_RECROW']._serialized_end=221
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=224
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
