# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import recommend_pb2 as recommend__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserRecs = channel.unary_unary(
                '/recommend.RecommendationService/GetUserRecs',
                request_serializer=recommend__pb2.UserRecRequest.SerializeToString,
                response_deserializer=recommend__pb2.RecListResponse.FromString,
                _registered_method=True)
        self.GetStateHotlist = channel.unary_unary(
                '/recommend.RecommendationService/GetStateHotlist',
                request_serializer=recommend__pb2.StateRequest.SerializeToString,
                response_deserializer=recommend__pb2.RecListResponse.FromString,
                _registered_method=True)
        self.PredictMatrix = channel.unary_stream(
                '/recommend.RecommendationService/PredictMatrix',
                request_serializer=recommend__pb2.StateRequest.SerializeToString,
                response_deserializer=recommend__pb2.RecRow.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserRecs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateHotlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserRecs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserRecs,
                    request_deserializer=recommend__pb2.UserRecRequest.FromString,
                    response_serializer=recommend__pb2.RecListResponse.SerializeToString,
            ),
            'GetStateHotlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateHotlist,
                    request_deserializer=recommend__pb2.StateRequest.FromString,
                    response_serializer=recommend__pb2.RecListResponse.SerializeToString,
            ),
            'PredictMatrix': grpc.unary_stream_rpc_method_handler(
                    servicer.PredictMatrix,
                    request_deserializer=recommend__pb2.StateRequest.FromString,
                    response_serializer=recommend__pb2.RecRow.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommend.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommend.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserRecs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommend.RecommendationService/GetUserRecs',
            recommend__pb2.UserRecRequest.SerializeToString,
            recommend__pb2.RecListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStateHotlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommend.RecommendationService/GetStateHotlist',
            recommend__pb2.StateRequest.SerializeToString,
            recommend__pb2.RecListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/recommend.RecommendationService/PredictMatrix',
            recommend__pb2.StateRequest.SerializeToString,
            recommend__pb2.RecRow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
