# Generated by Django 5.2 on 2025-04-21 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=22, primary_key=True, serialize=False, unique=True, verbose_name='Review ID')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Star Rating')),
                ('date', models.DateField(verbose_name='Review Date')),
                ('text', models.TextField(verbose_name='Review Text')),
                ('useful', models.PositiveIntegerField(default=0, verbose_name='Useful Votes')),
                ('funny', models.PositiveIntegerField(default=0, verbose_name='Funny Votes')),
                ('cool', models.PositiveIntegerField(default=0, verbose_name='Cool Votes')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business', verbose_name='Business Reviewed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Review Author')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user'], name='review_revi_user_id_1c40d7_idx'), models.Index(fields=['business'], name='review_revi_busines_96d39e_idx'), models.Index(fields=['stars'], name='review_revi_stars_bd5ed6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Tip Text')),
                ('date', models.DateField(verbose_name='Tip Date')),
                ('compliment_count', models.PositiveIntegerField(default=0, verbose_name='Compliment Count')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='business.business', verbose_name='Business Tipped')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL, verbose_name='Tip Author')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user'], name='review_tip_user_id_27ca54_idx'), models.Index(fields=['business'], name='review_tip_busines_546b02_idx')],
            },
        ),
    ]
