# Generated by Django 5.2 on 2025-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='auto_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Model automatic scoring'),
        ),
    ]
