name: Check Python formatting with autopep8

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install autopep8
        run: |
          python -m pip install --upgrade pip
          pip install autopep8

      - name: Check formatting
        run: |
          EXIT_CODE=0
          find . -type f -name "*.py" ! -name "urls.py" ! -name "models.py" ! -name "*.ipynb" ! -name "*_pb2_grpc.py" ! -name "*_pb2.py" -print0 | while IFS= read -r -d '' file; do
            autopep8 "$file" --exit-code --max-line-length=100 --ignore=E203,W503 --select=E,W --aggressive > /dev/null
            if [ $? -ne 0 ]; then
              echo "Formatting needed: $file"
              EXIT_CODE=1
            fi
          done

          exit $EXIT_CODE
